modLoader = "javafml"
loaderVersion = "{fmlVersionRange}"
issueTrackerURL = "https://github.com/thedarkcolour/ForestryCE/issues"

license = "GNU Lesser Public License v3"

[[mods]]
modId = "forestry_apiculture"
version = "${version}"
displayName = "Forestry: Apiculture"
displayURL = "https://github.com/thedarkcolour/ForestryCE"
logoFile = "forestry-ce-logo-banner.png"
authors = "thedarkcolour, SirSengir, mezz, Nedelosk"
description = '''
Bees, apiaries, alvearies and the beekeeping chain.
'''

[[dependencies.forestry_apiculture]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "${forgeVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.forestry_apiculture]]
modId = "forestry"
type = "REQUIRED"
versionRange = "[${version},]"
ordering = "AFTER"
side = "BOTH"
