package forestry.core.data;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Map;
import java.util.TreeMap;

import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;

import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

import forestry.Forestry;
import forestry.api.ForestryConstants;
import forestry.core.platform.registration.FeatureRegistry;
import forestry.core.platform.registration.IModFeature;
import forestry.core.platform.registration.ModFeatureRegistry;

/**
 * Writes the registry-id to owning-jar mapping that the build uses to decide which jar ships which
 * resource. Every feature already carries the id of the module that registered it, so this is read
 * out of the live registry rather than maintained by hand. A hand-written mapping would rot silently:
 * nothing in the build can tell a stale entry from a correct one.
 *
 * <p>Written next to {@code src/generated/resources} rather than inside it, so it never ships. It is
 * checked in, because the jar tasks need it without running the game, and it is regenerated by
 * {@code runData} - a diff in it means ownership moved.
 */
public class OwnershipManifest {
	// The data run's working directory is run/, not the project root, so the destination is passed in
	// as a system property by the runData task rather than assumed to be relative
	private static final Path OUTPUT = Path.of(System.getProperty("forestry.ownershipManifest", "ownership.json"));

	// Modules that ship in the base jar. Everything else is named after the jar it belongs to
	private static final Map<String, String> MODULE_TO_JAR = Map.ofEntries(
			Map.entry("core", "core"),
			Map.entry("fluids", "core"),
			Map.entry("factory", "core"),
			Map.entry("energy", "core"),
			Map.entry("storage", "core"),
			Map.entry("sorting", "core"),
			Map.entry("worktable", "core"),
			Map.entry("curios", "core"),
			Map.entry("apiculture", "apiculture"),
			Map.entry("arboriculture", "arboriculture"),
			Map.entry("lepidopterology", "lepidopterology"),
			Map.entry("farming", "agriculture"),
			Map.entry("cultivation", "agriculture"),
			Map.entry("mail", "mail"));

	private OwnershipManifest() {
	}

	/**
	 * Walks every registry each module owns and writes the manifest.
	 *
	 * <p>Two keys are written per entry. The bare id is what the path rules match on, and a key
	 * qualified by registry - {@code point_of_interest_type/forestry:escritoire} - is what resolves the
	 * cases the bare id cannot. Ex. the core escritoire block and the apiculture escritoire point of
	 * interest share a name and do not share a jar, so a bare id alone would answer one of them wrong.
	 */
	public static void write() {
		TreeMap<String, String> owners = new TreeMap<>();
		ArrayList<String> unmapped = new ArrayList<>();
		TreeMap<String, String> ambiguous = new TreeMap<>();

		for (ModFeatureRegistry modRegistry : ModFeatureRegistry.getRegistries().values()) {
			for (Map.Entry<ResourceLocation, FeatureRegistry> entry : modRegistry.getModules().entrySet()) {
				String jar = MODULE_TO_JAR.get(entry.getKey().getPath());
				if (jar == null) {
					unmapped.add(entry.getKey().toString());
					continue;
				}
				// Features are only part of what a module registers. Point of interest types take a
				// deferred register straight off the module, so walking the features alone left them
				// unowned - and an unowned id places no constraint on which jar may ship the file
				// naming it, which is how a core-only install ended up with an arboriculture poi tag
				for (Map.Entry<ResourceKey, DeferredRegister> registryEntry : entry.getValue().getRegistries().entrySet()) {
					String registry = registryEntry.getKey().location().getPath();
					for (DeferredHolder<?, ?> holder : (Collection<DeferredHolder<?, ?>>) registryEntry.getValue().getEntries()) {
						String id = holder.getId().toString();
						owners.put(registry + '/' + id, jar);

						String previous = owners.get(id);
						if (previous != null && !previous.equals(jar)) {
							// The bare key is the fallback for a reference whose registry is not known,
							// so it has to be the answer that constrains least. Ex. refractory_wax is a
							// core item and an apiculture particle; reading the bare key as apiculture
							// would say every recipe using the item needs the apiculture jar
							ambiguous.put(id, previous + " and " + jar);
							owners.put(id, "core".equals(previous) || "core".equals(jar) ? "core" : previous);
						} else {
							owners.put(id, jar);
						}
					}
				}
			}
		}

		if (!unmapped.isEmpty()) {
			// A new module with no jar assignment would silently drop every resource it owns
			throw new IllegalStateException("Module(s) with no jar in OwnershipManifest: " + unmapped);
		}
		// The bare id of an ambiguous pair answers one of its registries wrong, whichever way it lands.
		// Only the qualified key is trustworthy there, so say so rather than let it look settled
		ambiguous.forEach((id, jars) -> Forestry.LOGGER.warn("Ownership manifest: {} is registered by {}; only its registry-qualified keys are exact", id, jars));

		StringBuilder json = new StringBuilder("{\n");
		int i = 0;
		for (Map.Entry<String, String> entry : owners.entrySet()) {
			json.append("  \"").append(entry.getKey()).append("\": \"").append(entry.getValue()).append('"');
			json.append(++i == owners.size() ? "\n" : ",\n");
		}
		json.append("}\n");

		try {
			Files.createDirectories(OUTPUT.getParent());
			Files.writeString(OUTPUT, json.toString(), StandardCharsets.UTF_8);
		} catch (IOException e) {
			throw new RuntimeException("Failed to write the ownership manifest", e);
		}
		Forestry.LOGGER.info("Wrote ownership manifest: {} ids", owners.size());
	}
}
